Repository firstBitSportivnaya/PSSL, pull requests merged in 2024-11, with the labels that each got.

#136 fixed bugs
  src/cf/CommonForms/пбп_ФормаРазрешенияКонфликтовПредопределенныхЭлементов/Ext/Form/Module.bsl
  src/cf/CommonModules/пбп_ПредопределенныеЗначения/Ext/Module.bsl
Labels: bug

#138 docs: fix bsl syntax highlighting (#137)
  docs/ЗагрузкаФайлаЧерезТабличныйДокумент.md
  docs/МодификацияФорм.md
  docs/ПереопределениеМетодовБСП.md
  docs/ПодпискиНаСобытия.md
  docs/ПолучениеДанныхПоНастройкеОтбора.md
  docs/ПользовательскиеФункции.md
  docs/СоответствиеОбъектовИнформационнойБазы.md
Labels: documentation

#140 Added objects to subsystems
  src/cf/CommonModules/пбп_ОбновлениеИнформационнойБазыПБП/Ext/Module.bsl
  src/cf/Configuration.xml
  src/cf/Subsystems/пбп_МодификацияФорм.xml
  src/cf/Subsystems/пбп_ОбщегоНазначения.xml
  src/cf/Subsystems/пбп_ПредопределенныеЗначения.xml
Labels: invalid

#144 Added automatic creation of predefined elements
  docs/images/ФормаРазрешенияКонфликтов.png
  docs/ПредопределенныеЗначения.md
  src/cf/CommonForms/пбп_ФормаРазрешенияКонфликтовПредопределенныхЭлементов/Ext/Form.xml
  src/cf/CommonForms/пбп_ФормаРазрешенияКонфликтовПредопределенныхЭлементов/Ext/Form/Module.bsl
  src/cf/CommonModules/пбп_МетодыРегламентныхЗаданийСервер/Ext/Module.bsl
  src/cf/CommonModules/пбп_ОбновлениеИнформационнойБазыПБП/Ext/Module.bsl
  src/cf/CommonModules/пбп_ПредопределенныеЗначения/Ext/Module.bsl
  src/cf/CommonModules/пбп_ПредопределенныеЗначенияПереопределяемый/Ext/Module.bsl
  src/cf/CommonModules/пбп_ПредопределенныеЗначенияСлужебныйКлиент.xml
  src/cf/CommonModules/пбп_ПредопределенныеЗначенияСлужебныйКлиент/Ext/Module.bsl
  src/cf/CommonModules/пбп_СерверныеОповещения.xml
  src/cf/CommonModules/пбп_СерверныеОповещения/Ext/Module.bsl
  src/cf/CommonModules/пбп_СерверныеОповещенияСлужебный.xml
  src/cf/CommonModules/пбп_СерверныеОповещенияСлужебный/Ext/Module.bsl
  src/cf/Configuration.xml
  src/cf/Enums/пбп_ВидыОшибокПредопределенныхЭлементов.xml
  src/cf/ScheduledJobs/пбп_ЗаполнениеПредопределенныхЭлементов.xml
  src/cf/ScheduledJobs/пбп_ЗаполнениеПредопределенныхЭлементов/Ext/Schedule.xml
  src/cf/Subsystems/пбп_ОбщегоНазначения.xml
  src/cf/Subsystems/пбп_ПредопределенныеЗначения.xml
Labels: enhancement

#115 Create doc for subsystem integration management
  README.md
  docs/images/ERArchitectureIntegrationsSubsystem.svg
  docs/images/ЗаполнениеПредопределенныхПодсистемыИнтеграции.png
  docs/images/ЗапускКонфигуратораВПакетномРежиме.png
  docs/images/ПодключениеВнешнегоИсточникаДанныхНастройкиИнтеграции.png
  docs/images/ПодключениеВнешнейКомпонентыИзФайла.png
  docs/images/ПользовательскаяФункцияВыгрузкиВФайл.png
  docs/images/ПользовательскаяФункцияИнтеграционныйПоток.png
  docs/images/ПользовательскаяФункцияНастройкаИнтеграции.png
  docs/puml/ERArchitectureIntegrationsSubsystem.puml
  docs/УправлениеИнтеграциями.md
Labels: documentation
