Repository firstBitSportivnaya/PSSL, pull requests merged in 2024-09, with the labels that each got.

#91 Added functions for setting a mark for deletion and code refactoring
  .bsl-language-server.json
  docs/ПредопределенныеЗначения.md
  src/cf/Catalogs/пбп_ИнтегрируемыеСистемы/Ext/ManagerModule.bsl
  src/cf/Catalogs/пбп_ИнтегрируемыеСистемы/Forms/ФормаСписка/Ext/Form/Module.bsl
  src/cf/Catalogs/пбп_МетодыИнтеграции/Ext/ManagerModule.bsl
  src/cf/Catalogs/пбп_МетодыИнтеграции/Forms/ФормаСписка/Ext/Form/Module.bsl
  src/cf/Catalogs/пбп_НастройкиИнтеграции/Ext/ManagerModule.bsl
  src/cf/Catalogs/пбп_НастройкиИнтеграции/Forms/ФормаСписка/Ext/Form/Module.bsl
  src/cf/Catalogs/пбп_ТипСоответствияОбъектовИБ/Ext/ManagerModule.bsl
  src/cf/Catalogs/пбп_ТипСоответствияОбъектовИБ/Forms/ФормаСписка/Ext/Form/Module.bsl
  src/cf/ChartsOfCharacteristicTypes/пбп_ПредопределенныеЗначения/Forms/ФормаСписка/Ext/Form/Module.bsl
  src/cf/CommonModules/пбп_ИнтеграцииПереопределяемый.xml
  src/cf/CommonModules/пбп_ИнтеграцииПереопределяемый/Ext/Module.bsl
  src/cf/CommonModules/пбп_ОбновлениеИнформационнойБазыПБП/Ext/Module.bsl
  src/cf/CommonModules/пбп_ОбщегоНазначенияПовтИсп/Ext/Module.bsl
  src/cf/CommonModules/пбп_ОбщегоНазначенияСервер/Ext/Module.bsl
  src/cf/CommonModules/пбп_ОбщегоНазначенияСлужебный/Ext/Module.bsl
  src/cf/CommonModules/пбп_ПредопределенныеЗначения/Ext/Module.bsl
  src/cf/CommonModules/пбп_ПредопределенныеЗначенияПереопределяемый/Ext/Module.bsl
  src/cf/CommonModules/пбп_ТипСоответствияОбъектовИБПереопределяемый.xml
  src/cf/CommonModules/пбп_ТипСоответствияОбъектовИБПереопределяемый/Ext/Module.bsl
  src/cf/Configuration.xml
  src/cf/Subsystems/пбп_СоответствиеОбъектовИБ.xml
  src/cf/Subsystems/пбп_УправлениеИнтеграциями.xml
Labels: enhancement

#102 Исправлены пути к данным реквизитов формы
  src/cf/Catalogs/пбп_ИнтеграционныеПотоки/Forms/ФормаСписка/Ext/Form.xml
  src/cf/Catalogs/пбп_ИсторияИнтеграции/Forms/ФормаСписка/Ext/Form.xml
  src/cf/Catalogs/пбп_НастройкиИнтеграции/Forms/ФормаСписка/Ext/Form/Module.bsl
Labels: bug

#109 Create workflow for generate puml
  .github/workflows/generate-puml-svg.yml
  docs/ERДиаграммаПодсистемыУправленияИнтеграциями.md
  docs/images/ERArchitectureIntegrationsSubsystem.svg
  docs/puml/ERArchitectureIntegrationsSubsystem.puml
Labels: documentation
