Repository firstBitSportivnaya/PSSL, pull requests merged in 2024-12, with the labels that each got.

#163 refact predefined subsystem functions
  src/cf/CommonForms/пбп_ФормаРазрешенияКонфликтовПредопределенныхЭлементов/Ext/Form/Module.bsl
  src/cf/CommonModules/пбп_ОбновлениеИнформационнойБазыПБП/Ext/Module.bsl
  src/cf/CommonModules/пбп_ПредопределенныеЗначения/Ext/Module.bsl
  src/cf/CommonModules/пбп_ПредопределенныеЗначенияСлужебный/Ext/Module.bsl
  src/cf/Configuration.xml
  src/cf/Subsystems/пбп_ПредопределенныеЗначения.xml
Labels: enhancement

#157 first part of tests
  src/cfe/YAXUnit/CommonModules/ОМ_ПредопределенныеЗначения.xml
  src/cfe/YAXUnit/CommonModules/ОМ_ПредопределенныеЗначения/Ext/Module.bsl
  src/cfe/YAXUnit/CommonModules/ОМ_ПредопределенныеЗначенияВызовСервера.xml
  src/cfe/YAXUnit/CommonModules/ОМ_ПредопределенныеЗначенияВызовСервера/Ext/Module.bsl
  src/cfe/YAXUnit/CommonModules/ОМ_ПредопределенныеЗначенияСлужебный.xml
  src/cfe/YAXUnit/CommonModules/ОМ_ПредопределенныеЗначенияСлужебный/Ext/Module.bsl
  src/cfe/YAXUnit/CommonModules/пбп_ПредопределенныеЗначения.xml
  src/cfe/YAXUnit/CommonModules/пбп_ПредопределенныеЗначения/Ext/Module.bsl
  src/cfe/YAXUnit/CommonModules/пбп_ПредопределенныеЗначенияПереопределяемый.xml
  src/cfe/YAXUnit/CommonModules/пбп_ПредопределенныеЗначенияПереопределяемый/Ext/Module.bsl
  src/cfe/YAXUnit/Configuration.xml
Labels: tests

#171 Доработка сборки, добавление сценарных автотестов
  .github/workflows/sonar.yml
  features/Подсистема предопределенных значений.feature
  features/Подсистема управления интеграциями.feature
  jobConfiguration.json
  src/cf/Catalogs/пбп_ИнтеграционныеПотоки/Forms/ФормаСписка/Ext/Form.xml
  src/cf/Catalogs/пбп_ИсторияИнтеграции/Forms/ФормаСписка/Ext/Form.xml
  src/cf/Catalogs/пбп_НастройкиИнтеграции/Forms/ФормаСписка/Ext/Form.xml
  tools/VBParams.json
  tools/vrunner.json
  tools/yaxunit.json
Labels: enhancement

#167 improved funcs and refacted
  src/cf/CommonModules/пбп_ОбновлениеИнформационнойБазыПБП/Ext/Module.bsl
  src/cf/CommonModules/пбп_ОбщегоНазначенияСервер/Ext/Module.bsl
  src/cf/CommonModules/пбп_ПредопределенныеЗначения/Ext/Module.bsl
  src/cf/CommonModules/пбп_ПредопределенныеЗначенияВызовСервера/Ext/Module.bsl
  src/cf/CommonModules/пбп_ПредопределенныеЗначенияКлиент/Ext/Module.bsl
  src/cf/CommonModules/пбп_ПредопределенныеЗначенияПереопределяемый/Ext/Module.bsl
  src/cf/CommonModules/пбп_ПредопределенныеЗначенияСлужебный/Ext/Module.bsl
  src/cf/Configuration.xml
  src/cf/InformationRegisters/пбп_СостоянияПредопределенныхЭлементов/Ext/ManagerModule.bsl
  src/cfe/YAXUnit/CommonModules/ОМ_ПредопределенныеЗначенияСлужебный/Ext/Module.bsl
Labels: enhancement

#170 added new func select in object model
  src/cf/CommonModules/пбп_ИнтеграцииСервер/Ext/Module.bsl
  src/cf/CommonModules/пбп_ОбновлениеИнформационнойБазыПБП/Ext/Module.bsl
  src/cf/CommonModules/пбп_ПредопределенныеЗначенияСлужебный/Ext/Module.bsl
  src/cf/CommonModules/пбп_СхемыЗапросов/Ext/Module.bsl
  src/cf/Configuration.xml
  src/cfe/YAXUnit/CommonModules/пбп_ПредопределенныеЗначения/Ext/Module.bsl
Labels: enhancement

#173 refacted predefined functions and removed bugs
  src/cf/Catalogs/пбп_ИнтеграционныеПотоки/Ext/ObjectModule.bsl
  src/cf/Catalogs/пбп_ИнтегрируемыеСистемы/Ext/ObjectModule.bsl
  src/cf/Catalogs/пбп_НастройкиИнтеграции/Ext/ObjectModule.bsl
  src/cf/Catalogs/пбп_ТипСоответствияОбъектовИБ/Ext/ObjectModule.bsl
  src/cf/ChartsOfCharacteristicTypes/пбп_ПредопределенныеЗначения/Ext/ObjectModule.bsl
  src/cf/CommonModules/пбп_ОбновлениеИнформационнойБазыПБП/Ext/Module.bsl
  src/cf/CommonModules/пбп_ОбщегоНазначенияСервер/Ext/Module.bsl
  src/cf/CommonModules/пбп_ПредопределенныеЗначенияПереопределяемый/Ext/Module.bsl
  src/cf/CommonModules/пбп_ПредопределенныеЗначенияСлужебный/Ext/Module.bsl
  src/cf/CommonModules/пбп_СхемыЗапросов/Ext/Module.bsl
  src/cf/Configuration.xml
  src/cf/InformationRegisters/пбп_СостоянияПредопределенныхЭлементов/Ext/ManagerModule.bsl
Labels: bug, enhancement

#175 Исправлена ошибка указания порта в командах sftp-сервера
  src/cf/CommonModules/пбп_ИнтеграцииFTPSFTP/Ext/Module.bsl
Labels: bug

#177 Добавлена возможность выбора типа СУБД вручную на форме настройки
  src/cf/Catalogs/пбп_НастройкиИнтеграции.xml
  src/cf/Catalogs/пбп_НастройкиИнтеграции/Ext/ObjectModule.bsl
  src/cf/Catalogs/пбп_НастройкиИнтеграции/Forms/ФормаЭлемента/Ext/Form.xml
  src/cf/Catalogs/пбп_НастройкиИнтеграции/Forms/ФормаЭлемента/Ext/Form/Module.bsl
  src/cf/CommonModules/пбп_ИнтеграцииСервер/Ext/Module.bsl
  src/cf/CommonModules/пбп_ИнтеграцииСлужебный/Ext/Module.bsl
Labels: invalid
