Repository firstBitSportivnaya/PSSL, pull requests merged in 2025-04, with the labels that each got.

#246 Notification about predefined for full rights 242
  .gitattributes
  docs/ПредопределенныеЗначения.md
  src/cf/CommonModules/пбп_ОбновлениеИнформационнойБазыПБП/Ext/Module.bsl
  src/cf/CommonModules/пбп_ОбщегоНазначенияСервер/Ext/Module.bsl
  src/cf/CommonModules/пбп_Переадресация/Ext/Module.bsl
  src/cf/CommonModules/пбп_ПереадресацияПовтИсп/Ext/Module.bsl
  src/cf/CommonModules/пбп_ПредопределенныеЗначения/Ext/Module.bsl
  src/cf/CommonModules/пбп_ПредопределенныеЗначенияСлужебный/Ext/Module.bsl
  src/cf/Configuration.xml
Labels: Предопределенные значений

#228 first implementation
  docs/ПервоеВнедрение.md
  src/cf/CommonModules/пбп_ОбновлениеИнформационнойБазыПБП/Ext/Module.bsl
  src/cf/Configuration.xml
  src/epf/пбп_ПервоеВнедрение.xml
  src/epf/пбп_ПервоеВнедрение/Forms/Форма.xml
  src/epf/пбп_ПервоеВнедрение/Forms/Форма/Ext/Form.xml
  src/epf/пбп_ПервоеВнедрение/Forms/Форма/Ext/Form/Module.bsl
Labels: Общие

#251 Исправление ошибок сонара и дженкинса
  src/cf/CommonModules/пбп_Переадресация/Ext/Module.bsl
  src/cf/CommonModules/пбп_ПодключаемыеКоманды/Ext/Module.bsl
  src/cf/CommonModules/пбп_ПодключаемыеКомандыКлиент/Ext/Module.bsl
  src/cf/CommonModules/пбп_ПодключаемыеКомандыПереопределяемый/Ext/Module.bsl
  src/cf/CommonModules/пбп_ПодключаемыеКомандыСлужебныйКлиентСервер.xml
  src/cf/CommonModules/пбп_ПодключаемыеКомандыСлужебныйКлиентСервер/Ext/Module.bsl
  src/cf/Configuration.xml
  src/cf/DataProcessors/пбп_УниверсальнаяЗагрузкаИзФайлаЧерезТабличныйДокумент/Forms/Форма/Ext/Form/Module.bsl
Labels: Загрузка из таб.дока

#252 Fix errors
  src/cf/DataProcessors/пбп_УниверсальнаяЗагрузкаИзФайлаЧерезТабличныйДокумент/Forms/Форма/Ext/Form/Module.bsl
Labels: Загрузка из таб.дока

#254 Debug for users function
  src/cf/Catalogs/пбп_ИсторияИнтеграции/Forms/ФормаЭлемента/Ext/Form/Module.bsl
  src/cf/Catalogs/пбп_ПользовательскиеФункции.xml
  src/cf/Catalogs/пбп_ПользовательскиеФункции/Ext/ObjectModule.bsl
  src/cf/Catalogs/пбп_ПользовательскиеФункции/Forms/ФормаЭлемента/Ext/Form.xml
  src/cf/Catalogs/пбп_ПользовательскиеФункции/Forms/ФормаЭлемента/Ext/Form/Module.bsl
  src/cf/Catalogs/пбп_ПользовательскиеФункции/Templates/КаркасОтладки.xml
  src/cf/Catalogs/пбп_ПользовательскиеФункции/Templates/КаркасОтладки/Ext/Template.bin
  src/cf/CommonForms/пбп_ФормаПодключенияКБазе1С/Ext/Form.xml
  src/cf/CommonForms/пбп_ФормаПодключенияКБазе1С/Ext/Form/Module.bsl
  src/cf/CommonModules/пбп_МодификацияКонфигурацииКлиентПереопределяемый/Ext/Module.bsl
  src/cf/CommonModules/пбп_ОбновлениеИнформационнойБазыПБП/Ext/Module.bsl
  src/cf/CommonPictures/пбп_Отладка.xml
  src/cf/CommonPictures/пбп_Отладка/Ext/Picture.xml
  src/cf/CommonPictures/пбп_Отладка/Ext/Picture/Picture.png
  src/cf/Configuration.xml
  src/cf/Subsystems/пбп_ПользовательскиеФункции.xml
Labels: Пользовательские функции

#266 исправил все замечания
  src/cf/CommonForms/пбп_ФормаРазрешенияКонфликтовПредопределенныхЭлементов/Ext/Form/Module.bsl
  src/cf/CommonModules/пбп_ОбновлениеИнформационнойБазыПБП/Ext/Module.bsl
  src/cf/CommonModules/пбп_ПредопределенныеЗначенияСлужебный/Ext/Module.bsl
  src/cf/Configuration.xml
Labels: Предопределенные значений
