Repository firstBitSportivnaya/PSSL, pull requests merged in 2025-01, with the labels that each got.

#183 Исправление преобразования значений Булево в загрузке файлов
  src/cf/CommonModules/пбп_ЗагрузкаФайлаЧерезТабличныйДокументСервер/Ext/Module.bsl
Labels: bug

#176 added descriptions about query schema
  README.md
  docs/images/ОбъектнаяМодельСхемаЗапроса.svg
  docs/puml/ОбъектнаяМодельСхемаЗапроса.puml
  docs/СхемыЗапросов.md
Labels: documentation

#186 Исправление ошибки форматирования полей сообщений sftp
  src/cf/CommonModules/пбп_ИнтеграцииСлужебный/Ext/Module.bsl
Labels: bug

#184 Добавление структуры упорядочивания полей
  src/cf/CommonModules/пбп_ИнтеграцииСервер/Ext/Module.bsl
  src/cf/CommonModules/пбп_ОбновлениеИнформационнойБазыПБП/Ext/Module.bsl
  src/cf/Configuration.xml
Labels: enhancement

#191 fixed bug with empty parent's id
  src/cf/CommonModules/пбп_ОбновлениеИнформационнойБазыПБП/Ext/Module.bsl
  src/cf/CommonModules/пбп_ПредопределенныеЗначенияСлужебный/Ext/Module.bsl
  src/cf/Configuration.xml
Labels: bug

#190 Добавление подсистемы валидации по схеме спеки Open API
  src/cf/CommonModules/пбп_ВалидаторПакетов.xml
  src/cf/CommonModules/пбп_ВалидаторПакетов/Ext/Module.bsl
  src/cf/CommonModules/пбп_ВалидаторПакетовПовтИсп.xml
  src/cf/CommonModules/пбп_ВалидаторПакетовПовтИсп/Ext/Module.bsl
  src/cf/CommonModules/пбп_ВалидаторПакетовСлужебный.xml
  src/cf/CommonModules/пбп_ВалидаторПакетовСлужебный/Ext/Module.bsl
  src/cf/CommonModules/пбп_ОбновлениеИнформационнойБазыПБП/Ext/Module.bsl
  src/cf/CommonModules/пбп_ОбщегоНазначенияСервер/Ext/Module.bsl
  src/cf/CommonModules/пбп_Переадресация/Ext/Module.bsl
  src/cf/Configuration.xml
  src/cf/Subsystems/пбп_УправлениеИнтеграциями.xml
Labels: new function

#198 Rework integration history
  src/cf/Catalogs/пбп_ИсторияИнтеграции.xml
  src/cf/Catalogs/пбп_ИсторияИнтеграции/Ext/ManagerModule.bsl
  src/cf/Catalogs/пбп_ИсторияИнтеграции/Forms/ФормаЭлемента/Ext/Form.xml
  src/cf/CommonModules/пбп_ВалидаторПакетов/Ext/Module.bsl
  src/cf/CommonModules/пбп_ИнтеграцииСлужебный/Ext/Module.bsl
  src/cf/CommonModules/пбп_ОбновлениеИнформационнойБазыПБП/Ext/Module.bsl
  src/cf/Configuration.xml
  src/cf/Enums/пбп_СозданОбновлен.xml
Labels: enhancement

#199 Add history integration time to thread
  src/cf/Catalogs/пбп_ИнтеграционныеПотоки.xml
  src/cf/Catalogs/пбп_ИнтеграционныеПотоки/Forms/ФормаЭлемента/Ext/Form.xml
  src/cf/Catalogs/пбп_ИсторияИнтеграции/Ext/ManagerModule.bsl
  src/cf/CommonModules/пбп_ИнтеграцииСлужебный/Ext/Module.bsl
  src/cf/CommonModules/пбп_ОбновлениеИнформационнойБазыПБП/Ext/Module.bsl
  src/cf/Configuration.xml
Labels: enhancement
