Repository firstBitSportivnaya/PSSL, pull requests merged in 2025-03, with the labels that each got.

#229 Доработка настроек интеграции, добавление плана обмена и тех настройки
  src/cf/Catalogs/пбп_НастройкиИнтеграции.xml
  src/cf/Catalogs/пбп_НастройкиИнтеграции/Ext/ObjectModule.bsl
  src/cf/Catalogs/пбп_НастройкиИнтеграции/Forms/ФормаСписка/Ext/Form.xml
  src/cf/Catalogs/пбп_НастройкиИнтеграции/Forms/ФормаЭлемента/Ext/Form.xml
  src/cf/Catalogs/пбп_НастройкиИнтеграции/Forms/ФормаЭлемента/Ext/Form/Module.bsl
  src/cf/CommonModules/пбп_ОбновлениеИнформационнойБазыПБП/Ext/Module.bsl
  src/cf/CommonModules/пбп_Переадресация/Ext/Module.bsl
  src/cf/Configuration.xml
Labels: Интеграции

#234 Доработан регистр соответствия объектов интегрируемых систем
  src/cf/CommonModules/пбп_ОбновлениеИнформационнойБазыПБП/Ext/Module.bsl
  src/cf/Configuration.xml
  src/cf/InformationRegisters/пбп_СоответствиеОбъектовИнтегрируемыхСистем.xml
  src/cf/InformationRegisters/пбп_СоответствиеОбъектовИнтегрируемыхСистем/Forms/ФормаЗаписи.xml
  src/cf/InformationRegisters/пбп_СоответствиеОбъектовИнтегрируемыхСистем/Forms/ФормаЗаписи/Ext/Form.xml
  src/cf/InformationRegisters/пбп_СоответствиеОбъектовИнтегрируемыхСистем/Forms/ФормаЗаписи/Ext/Form/Module.bsl
  src/cf/InformationRegisters/пбп_СоответствиеОбъектовИнтегрируемыхСистем/Forms/ФормаСвязанныхЗаписейИстории.xml
  src/cf/InformationRegisters/пбп_СоответствиеОбъектовИнтегрируемыхСистем/Forms/ФормаСвязанныхЗаписейИстории/Ext/Form.xml
  src/cf/InformationRegisters/пбп_СоответствиеОбъектовИнтегрируемыхСистем/Forms/ФормаСвязанныхЗаписейИстории/Ext/Form/Module.bsl
  src/cf/InformationRegisters/пбп_СоответствиеОбъектовИнтегрируемыхСистем/Forms/ФормаСписка.xml
  src/cf/InformationRegisters/пбп_СоответствиеОбъектовИнтегрируемыхСистем/Forms/ФормаСписка/Ext/Form.xml
Labels: Интеграции

#235 В историю интеграции добавлен просмотр версии объектов обмена
  src/cf/Catalogs/пбп_ИнтеграционныеПотоки.xml
  src/cf/Catalogs/пбп_ИнтеграционныеПотоки/Forms/ФормаЭлемента/Ext/Form.xml
  src/cf/Catalogs/пбп_ИнтеграционныеПотоки/Forms/ФормаЭлемента/Ext/Form/Module.bsl
  src/cf/Catalogs/пбп_ИсторияИнтеграции.xml
  src/cf/Catalogs/пбп_ИсторияИнтеграции/Forms/ФормаЭлемента/Ext/Form.xml
  src/cf/Catalogs/пбп_ИсторияИнтеграции/Forms/ФормаЭлемента/Ext/Form/Module.bsl
  src/cf/CommonModules/пбп_ИнтеграцииСервер/Ext/Module.bsl
  src/cf/CommonModules/пбп_ИнтеграцииСлужебный/Ext/Module.bsl
  src/cf/CommonModules/пбп_ОбновлениеИнформационнойБазыПБП/Ext/Module.bsl
  src/cf/CommonModules/пбп_ОбщегоНазначенияПовтИсп/Ext/Module.bsl
  src/cf/Configuration.xml
Labels: Интеграции

#236 Улучшение формы пользовательских функций
  src/cf/Catalogs/пбп_ПользовательскиеФункции/Forms/ФормаЭлемента/Ext/Form.xml
  src/cf/CommonModules/пбп_ОбновлениеИнформационнойБазыПБП/Ext/Module.bsl
  src/cf/Configuration.xml
Labels: Пользовательские функции

#237 Убрана проверка на сопоставление по наименованию
  src/cf/CommonModules/пбп_ЗагрузкаФайлаЧерезТабличныйДокументСервер/Ext/Module.bsl
  src/cf/CommonModules/пбп_ОбновлениеИнформационнойБазыПБП/Ext/Module.bsl
  src/cf/Configuration.xml
Labels: Загрузка из таб.дока

#240 Повысил версию конфигурации и исправил ошибки сонара
  src/cf/CommonModules/пбп_ИнтеграцииСлужебный/Ext/Module.bsl
  src/cf/CommonModules/пбп_ОбновлениеИнформационнойБазыПБП/Ext/Module.bsl
  src/cf/Configuration.xml
Labels: Интеграции

#244 Добавлен метод для работы с формами
  src/cf/CommonModules/пбп_РаботаСФормами/Ext/Module.bsl
Labels: Модификация форм

#245 Доработан программный интерфейс подсистемы интеграций
  src/cf/Subsystems/пбп_УправлениеИнтеграциями/Ext/CommandInterface.xml
Labels: Интеграции
