Repository firstBitSportivnaya/PSSL, pull requests merged in 2025-07, with the labels that each got.

#293 Для полей заголовок сделан необязательным
  src/cf/CommonModules/пбп_РаботаСФормами/Ext/Module.bsl
Labels: Модификация форм

#290 Исправлены права на регистр Соответствий объектов ИБ
  src/cf/Roles/пбп_РедактированиеРегистраСведенийСоответствияОбъектовИБ/Ext/Rights.xml
Labels: Предопределенные значений

#294 Обновлен просмотрщик xml-файлов
  src/cf/CommonTemplates/пбп_XMLEditor/Ext/Template.bin
Labels: Интеграции

#292 Добавлена очистка основных реквизитов настроек интеграции
  docs/УправлениеИнтеграциями.md
  src/cf/Catalogs/пбп_НастройкиИнтеграции/Ext/ManagerModule.bsl
  src/cf/CommonModules/пбп_Переадресация/Ext/Module.bsl
Labels: Интеграции

#302 Добавление проверки получения данных из БХ по настройке интеграции
  src/cf/CommonModules/пбп_ИнтеграцииСлужебный/Ext/Module.bsl
Labels: Интеграции

#306 Удалены устаревшие методы
  src/cf/CommonModules/пбп_МодификацияКонфигурацииПереопределяемый/Ext/Module.bsl
Labels: Модификация форм

#303 Исправление ошибок регламентного задания очистки интеграции
  src/cf/Catalogs/пбп_ИсторияИнтеграции/Ext/ManagerModule.bsl
  src/cf/Catalogs/пбп_ИсторияИнтеграции/Forms/ФормаСписка/Ext/Form/Module.bsl
Labels: Интеграции

#314 210 interface for registers
  src/cf/Catalogs/пбп_НастройкиИнтеграции.xml
  src/cf/Catalogs/пбп_НастройкиИнтеграции/Ext/ObjectModule.bsl
  src/cf/Catalogs/пбп_НастройкиИнтеграции/Forms/ФормаЭлемента/Ext/Form.xml
  src/cf/CommonModules/пбп_ИнтеграцииСервер/Ext/Module.bsl
  src/cf/CommonModules/пбп_ИнтеграцииСлужебный/Ext/Module.bsl
  src/cf/CommonModules/пбп_ОбщегоНазначенияПовтИсп/Ext/Module.bsl
  src/cf/CommonModules/пбп_ОбщегоНазначенияСервер/Ext/Module.bsl
  src/cf/InformationRegisters/пбп_ИсторияЗагрузкиФайлов/Ext/ManagerModule.bsl
  src/cf/InformationRegisters/пбп_СоответствияОбъектовИБ.xml
  src/cf/InformationRegisters/пбп_СоответствияОбъектовИБ/Ext/ManagerModule.bsl
Labels: Общие

#320 fixed bugs
  src/cf/CommonModules/пбп_ОбновлениеИнформационнойБазыПБП/Ext/Module.bsl
  src/cf/CommonModules/пбп_ПредопределенныеЗначенияСлужебный/Ext/Module.bsl
  src/cf/Configuration.xml
Labels: Предопределенные значений

#323 Увеличена длина наименования до 100
  src/cf/Catalogs/пбп_ТипСоответствияОбъектовИБ.xml
Labels: Общие

#325 removed exclamation mark
  src/cf/CommonModules/пбп_ОбновлениеИнформационнойБазыПБП/Ext/Module.bsl
  src/cf/CommonModules/пбп_ПредопределенныеЗначения/Ext/Module.bsl
  src/cf/Configuration.xml
Labels: Предопределенные значений
