Repository firstBitSportivnaya/PSSL, pull requests merged in 2025-02, with the labels that each got.

#206 Добавлено расписание регл заданий в интеграционные потоки
  src/cf/Catalogs/пбп_ИнтеграционныеПотоки.xml
  src/cf/Catalogs/пбп_ИнтеграционныеПотоки/Ext/ObjectModule.bsl
  src/cf/Catalogs/пбп_ИнтеграционныеПотоки/Forms/ФормаЭлемента/Ext/Form/Module.bsl
  src/cf/Catalogs/пбп_ИсторияИнтеграции.xml
  src/cf/Catalogs/пбп_ИсторияИнтеграции/Ext/ManagerModule.bsl
  src/cf/Catalogs/пбп_НастройкиИнтеграции.xml
  src/cf/CommonModules/пбп_МетодыРегламентныхЗаданийСервер/Ext/Module.bsl
  src/cf/CommonModules/пбп_ОбновлениеИнформационнойБазыПБП/Ext/Module.bsl
  src/cf/CommonModules/пбп_ПредопределенныеЗначенияПереопределяемый/Ext/Module.bsl
  src/cf/Configuration.xml
Labels: enhancement

#207 Small enchantments subsystem man int
  src/cf/Catalogs/пбп_ИсторияИнтеграции.xml
  src/cf/Catalogs/пбп_ИсторияИнтеграции/Forms/ФормаЭлемента/Ext/Form.xml
  src/cf/Catalogs/пбп_ИсторияИнтеграции/Forms/ФормаЭлемента/Ext/Form/Module.bsl
  src/cf/Catalogs/пбп_НастройкиИнтеграции/Forms/ФормаСписка/Ext/Form.xml
  src/cf/Catalogs/пбп_НастройкиИнтеграции/Forms/ФормаЭлемента/Ext/Form/Module.bsl
  src/cf/CommonModules/пбп_ВалидаторПакетовСлужебный/Ext/Module.bsl
  src/cf/CommonModules/пбп_ИнтеграцииСервер/Ext/Module.bsl
  src/cf/CommonModules/пбп_ИнтеграцииСлужебный/Ext/Module.bsl
  src/cf/CommonModules/пбп_ОбновлениеИнформационнойБазыПБП/Ext/Module.bsl
  src/cf/CommonModules/пбп_ПереадресацияКлиентСервер/Ext/Module.bsl
  src/cf/Configuration.xml
Labels: bug, enhancement

#209 Добавлен РС истории загрузки файлов и добавлены поля поиска в загрузку
  src/cf/CommonModules/пбп_ЗагрузкаФайлаЧерезТабличныйДокументСервер/Ext/Module.bsl
  src/cf/CommonModules/пбп_ИнтеграцииСлужебный/Ext/Module.bsl
  src/cf/CommonModules/пбп_ОбновлениеИнформационнойБазыПБП/Ext/Module.bsl
  src/cf/Configuration.xml
  src/cf/InformationRegisters/пбп_ИсторияЗагрузкиФайлов.xml
  src/cf/InformationRegisters/пбп_ИсторияЗагрузкиФайлов/Ext/ManagerModule.bsl
  src/cf/Roles/пбп_РедактированиеИсторииЗагрузкиФайлов.xml
  src/cf/Roles/пбп_РедактированиеИсторииЗагрузкиФайлов/Ext/Rights.xml
  src/cf/Roles/пбп_ЧтениеИсторииЗагрузкиФайлов.xml
  src/cf/Roles/пбп_ЧтениеИсторииЗагрузкиФайлов/Ext/Rights.xml
  src/cf/Subsystems/пбп_УправлениеИнтеграциями.xml
Labels: enhancement

#201 added Openapi specification visualization to Swagger UI
  src/cf/CommonModules/пбп_ОбновлениеИнформационнойБазыПБП/Ext/Module.bsl
  src/cf/CommonModules/пбп_ПостроительСпецификацииOpenAPI.xml
  src/cf/CommonModules/пбп_ПостроительСпецификацииOpenAPI/Ext/Module.bsl
  src/cf/CommonModules/пбп_ПостроительСпецификацииOpenAPIПереопределяемый.xml
  src/cf/CommonModules/пбп_ПостроительСпецификацииOpenAPIПереопределяемый/Ext/Module.bsl
  src/cf/CommonModules/пбп_ПостроительСпецификацииOpenAPIПовтИсп.xml
  src/cf/CommonModules/пбп_ПостроительСпецификацииOpenAPIПовтИсп/Ext/Module.bsl
  src/cf/CommonTemplates/пбп_СпецификацияИконка16СтраницыREST.xml
  src/cf/CommonTemplates/пбп_СпецификацияИконка16СтраницыREST/Ext/Template.bin
  src/cf/CommonTemplates/пбп_СпецификацияИконка32СтраницыREST.xml
  src/cf/CommonTemplates/пбп_СпецификацияИконка32СтраницыREST/Ext/Template.bin
  src/cf/CommonTemplates/пбп_СпецификацияСкриптыСтраницыREST.xml
  src/cf/CommonTemplates/пбп_СпецификацияСкриптыСтраницыREST/Ext/Template.txt
  src/cf/CommonTemplates/пбп_СпецификацияСтилиСтраницыREST.xml
  src/cf/CommonTemplates/пбп_СпецификацияСтилиСтраницыREST/Ext/Template.txt
  src/cf/CommonTemplates/пбп_СпецификацияСтраницаREST.xml
  src/cf/CommonTemplates/пбп_СпецификацияСтраницаREST/Ext/Template.txt
  src/cf/Configuration.xml
  src/cf/Subsystems/пбп_УправлениеИнтеграциями.xml
  src/cfe/YAXUnit/CommonModules/ОМ_ПостроительСпецификацииOpenAPI.xml
  src/cfe/YAXUnit/CommonModules/ОМ_ПостроительСпецификацииOpenAPI/Ext/Module.bsl
  src/cfe/YAXUnit/CommonModules/пбп_ПостроительСпецификацииOpenAPI.xml
  src/cfe/YAXUnit/CommonModules/пбп_ПостроительСпецификацииOpenAPI/Ext/Module.bsl
  src/cfe/YAXUnit/Configuration.xml
Labels: new function

#218 Interface for user functions in integration subsystem
  src/cf/Catalogs/пбп_ИнтеграционныеПотоки/Forms/ФормаЭлемента/Ext/Form/Module.bsl
  src/cf/Catalogs/пбп_ПользовательскиеФункции.xml
  src/cf/Catalogs/пбп_ПользовательскиеФункции/Ext/ManagerModule.bsl
  src/cf/Catalogs/пбп_ПользовательскиеФункции/Forms/ФормаЭлемента/Ext/Form.xml
  src/cf/CommonModules/пбп_ИнтеграцииСервер/Ext/Module.bsl
  src/cf/CommonModules/пбп_ИнтеграцииСлужебный/Ext/Module.bsl
  src/cf/CommonModules/пбп_МетодыРегламентныхЗаданийСервер/Ext/Module.bsl
  src/cf/CommonModules/пбп_ОбновлениеИнформационнойБазыПБП/Ext/Module.bsl
  src/cf/Configuration.xml
  src/cf/Enums/пбп_КонтекстыВыполненияПользовательскихФункций.xml
Labels: Интеграции

#223 Add check to existence method
  src/cf/CommonModules/пбп_МодификацияКонфигурацииКлиентПереопределяемый/Ext/Module.bsl
  src/cf/CommonModules/пбп_МодификацияКонфигурацииКлиентПовтИсп/Ext/Module.bsl
  src/cf/CommonModules/пбп_МодификацияКонфигурацииПереопределяемый/Ext/Module.bsl
  src/cf/CommonModules/пбп_ОбновлениеИнформационнойБазыПБП/Ext/Module.bsl
  src/cf/CommonModules/пбп_ОбщегоНазначенияВызовСервера/Ext/Module.bsl
  src/cf/Configuration.xml
  src/cf/Documents/ДемоРаботаСФормами/Forms/ФормаДокумента/Ext/Form.xml
  src/cf/Documents/ДемоРаботаСФормами/Forms/ФормаДокумента/Ext/Form/Module.bsl
Labels: Модификация форм

#225 Исправлено использование директив компиляции мобильного приложения
  src/cf/CommonModules/пбп_МодификацияКонфигурацииКлиентПереопределяемый/Ext/Module.bsl
Labels: Модификация форм
